# Generated by Django 6.0.2 on 2026-03-02 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_projects_pr_user_id_3cbd31_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="project",
            name="projects_pr_client__06571b_idx",
        ),
    ]
