# Generated by Django 6.0.2 on 2026-02-28 08:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="client",
            index=models.Index(
                fields=["user", "-created_at"], name="clients_cli_user_id_ebd3f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(fields=["name"], name="clients_cli_name_5ab7bc_idx"),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(fields=["email"], name="clients_cli_email_56b9fc_idx"),
        ),
    ]
